# Generated by Django 3.1.5 on 2021-01-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_auto_20210131_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='name',
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo',
            field=models.IntegerField(db_column='Codigo', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='nome',
            field=models.CharField(db_column='Nome', default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.CharField(db_column='Uf', default=1, max_length=2),
            preserve_default=False,
        ),
    ]
